services:
  redis:
   image: redis
   ports:
     - "6379:6379"
   healthcheck:
   test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
   timeout: 10s
   retries: 10
   extends:
    file: common-config.yml
    service: network-deploy-service
  
   eurekaserver:
    image: "samseyi672/eurekaserver-MobileMoneyDiscoveryServerMs:0.0.1-SNAPSHOT"
    container_name: eurekaserver-ms
    ports:
      - "8070:8070"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  mobilemoneyaccount_db:
    container_name: mobilemoneyaccountdb
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: mobilemoneyaccountdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  mobilemoneytransaction_db:
    container_name: mobilemoneytransactiondb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mobilemoneytransactiondb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "samseyi672/configserver-MobileMoneyConfigServerMs:0.0.1-SNAPSHOT"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  mobilemoneyaccount_ms:
    image: "samseyi672/mobilemoneyaccountms-MobileMoneyAccountMs:0.0.1-SNAPSHOT"
    container_name: mobilemoneyaccountms-ms
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: "mobilemoneyaccountms"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mobilemoneyaccount_db:3306/mobilemoneyaccountdb"
    depends_on:
      mobilemoneyaccount_db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  mobilemoneytransaction_ms:
    image: "samseyi672/mobilemoneytransactionms-MobileMoneyTransactionMs:0.0.1-SNAPSHOT"
    container_name: mobilemoneytransactionms-ms
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: "mobilemoneytransactionms"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mobilemoneytransaction_db:3306/mobilemoneytransactiondb"
    depends_on:
      mobilemoneytransaction_db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  mobilemoneygateway_ms:
    image: "samseyi672/mobilemoneygatewayms-MobileMoneyGatewayMs:0.0.1-SNAPSHOT"
    container_name: mobilemoneygateway-ms
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: "mobilemoneygatewayms"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mobilemoneytransaction_db:3306/mobilemoneytransactiondb"
    depends_on:
      mobilemoneytransaction_db:
        condition: service_healthy
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  mobilemoney:
    driver: "bridge"















































































































































































































































































































































































